### ISSUE TITLE
random access to character maps

### ISSUE THREAD

**Issue by aroman** [loodakrawa/SpriterDotNet#101]
thanks for this great library!

i am wondering why the character map feature is only exposed via push/pop. wouldn't it be far more useful to be able to apply a character map by name or index?

obviously i could write a hacky workaround to do this using push and pop, but why not simply have a `useCharacterMap` function?

**Comment by loodakrawa** [comment]
Glad you like it!

Character maps are designed to be layered - some sprites might be transparent in one layer and non transparent in other, etc. So a stack structure is the most appropriate structure for this. While theoretically applying them by name or index could be part of the library - it seems like an edge case. However, if you do end up implementing this, consider submitting a PR.
