### ISSUE TITLE
Total bounding area

### ISSUE THREAD

**Issue by Mathetis** [loodakrawa/SpriterDotNet#104]
Hey, is there an easy way to find the total maximum bounding area of an animation? Or all animations for a sprite instance?

Thanks for any assistance.

**Comment by loodakrawa** [comment]
Hi,

The easiest way I can think of is - running the simulation once after loading (with a small time delta) and using [GetBoundingBox](https://github.com/loodakrawa/SpriterDotNet/blob/8f428c6373afe9bc6f42947239bcaa73f903685f/SpriterDotNet.MonoGame/MonoGameAnimator.cs#L136) on all the sprites in each frame. The max bounding box for an animation is the union of all the bounding boxes of all sprites across all frames.

Hope this helps.

**Comment by Mathetis** [comment]
It does, thank you.
