### ISSUE TITLE
Animator always null in Start method(Unity)

### ISSUE THREAD

**Issue by BDeshiDev** [loodakrawa/SpriterDotNet#109]
I've noticed that whenever I try to do this:
UnityAnimator anim = GetComponent<SpriterDotNetBehaviour>().Animator;
in the start() method, it's always null But it works ithe first time update method is called. Is this fixable? It's kind of annoying call getcomponent on the update method.

**Comment by JuanGdelaCruz** [comment]
Hi,
It has a simple fix.
Open the SpriteDotNetBehaviour script.
Change the Start() method for Awake().

**Comment by BDeshiDev** [comment]
Thanks!
