### ISSUE TITLE
Enhancement: Using Built-in Unity Animator & Animations

### ISSUE THREAD

**Issue by Pikl** [loodakrawa/SpriterDotNet#12]
Hello, I've recently downloaded the Unity Package to implement in our game because the latest spriter update has broken our animations using the Spriter2UnityDX plugin.

Everything that you've done is pretty radical, but one thing that I loved about Spriter2UnityDX was that it built unity animations and allowed their use in the Animator, so that we could control our animations with state machines and use fancy features like Foot IK.

After a quick look, it looks like this one does all of the work itself which is impressive, but I'm not sure how I could use the built in components with it.

Have you got plans to add support for these things? Or have you got any advice on how to do it myself?

**Comment by loodakrawa** [comment]
Hi,

The goal of SpriterDotNet is to implement all the features from Spriter in a platform agnostic way. In other words, it tries to do all the work independently of any platform. It uses the concrete platforms almost exclusively as a renderer, at least regarding actual animations. The downside of this approach is the inability to use some of the platform's feature (like Unity's animation system).

On the other hand, some of the features should be rather straightforward to implement directly in the lib - like the state machine driven animations. This is definitely a great suggestion and I'll definitely add it in the near future.

As for other features, it really depends on the feature. Feel free to suggest specific features or implement them yourself and submit them via a pull request - contributions are always welcome. If you decide to contribute, I'd be happy to discuss and offer help either here or on the Spriter forum.

Cheers
