### ISSUE TITLE
Unity: keep transforms on prefab replace

### ISSUE THREAD

**Issue by loodakrawa** [loodakrawa/SpriterDotNet#17]

**Comment by esDotDev** [comment]
It would also be nice if you could transfer over any attached components and their values (if possible?).

For example, we would like to attach a script from the PrefabEvolution, which allows us to nest this Prefabs within another, but right now, the PrefabEvolution component is stripped out each time the animation is regenerated.

**Comment by loodakrawa** [comment]
AFAIK, it is not possible to transfer components from one object to another without some kind of reflection / deep copy magic. I suggest using the import hook to add desired components. See:
https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet.Unity/Assets/SpriterDotNet/SpriterImporter.cs#L26

**Comment by esDotDev** [comment]
Can't you just clone the existing prefab and use it as a base? Pretty sure that's how the other plugin works, and it supports  the use case I'm describing.
https://github.com/Dharengo/Spriter2UnityDX/blob/master/Assets/Spriter2UnityDX/Editor/PrefabBuilder.cs
Cheers,

**Comment by loodakrawa** [comment]
Good idea! I was thinking in terms of copying over Components from the old prefab to the new instead of the other way around. I'll implement it by replacing the child gameobjects of the old prefab with the children of the newly generated one (+ replacing the SpriterDotNetBehaviour). This way the existing prefab is going to keep all the components while getting updated to the latest version.

**Comment by esDotDev** [comment]
Nice :) Thanks again for all the hard work
