### ISSUE TITLE
Support for TexturePacker / 2dToolKit

### ISSUE THREAD

**Issue by treefortress** [loodakrawa/SpriterDotNet#34]
We'd like to use an external Sprite Packing tool (like TexturePacker, or 2dToolKit) to create our texture atlases, and wondering how we could integrate that with SpriterDotNet.

Any tips on where to start?

**Comment by loodakrawa** [comment]
This answer assumes you're using the Unity plugin.

I suggest the most obvious approach would be modifying the SpriterImporter, more specifically the part where the assets get loaded (provided you can get a Sprite reference from your atlas):

https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet.Unity/Assets/SpriterDotNet/SpriterImporter.cs#L226

Also, I'll close this as it is not an actual issue (although we can continue this conversation). In the future, it would be better to ask such questions on the forum thread and open actual issues here.

**Comment by treefortress** [comment]
Thanks for the pointer. I was able to get this working fairly easily. Here's a quick example of anyone else needs to do this:
'''
private static T LoadContent<T>(string path) where T : UnityEngine.Object
        {
            T asset;

            //Try and load from TexturePacker
            var atlasPaths = new List<string> {
                "Assets/_Internal/Textures/Enemies/Enemies",
                "Assets/_Internal/Textures/Followers/Followers"
            };
            var imageSuffix = ".png";
            var splitPath = path.Split('/').ToList();
            var spriteNames = new List<string>();
            while (splitPath.Count > 0) {
                spriteNames.Add(string.Join("-", splitPath.ToArray()));
                splitPath.RemoveAt(0);
            }
            foreach (var p in atlasPaths) {
                var sprites = AssetDatabase.LoadAllAssetsAtPath(p + imageSuffix).OfType<Sprite>().ToList();
                var material = AssetDatabase.LoadAssetAtPath<Material>(p + ".mat");
                //Check each possible match, across each sprite
                foreach (var name in spriteNames) {
                    foreach (var s in sprites) {
                        if ((s.name + imageSuffix) == name) {
                            currentMaterial = material;
                            return s as T;
                        }
                    }
                }
            }

            asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null) Debug.Log("Missing Asset: " + path);

            return asset;
        }
'''

The only trick, for our use case (Normal Map support) is that we still need to apply the matching material. So we save off currentMaterial in the LoacContent function. and then apply it in CreateSprites()
'''
 private static void CreateSprites(){
...
    var r = child.AddComponent<SpriteRenderer>();
    if (currentMaterial != null) {
        r.material = currentMaterial;
    }
}

**Comment by treefortress** [comment]
Hmm, looks like I spoke too soon. Everything works great, until I close the editor and re-open. Then it all gets seems to get corrupted, and starts throwing errors:

ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[UnityEngine.Sprite,UnityEngine.Sprite].ContainsKey (UnityEngine.Sprite key) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:458)
SpriterDotNet.SpriterAnimator`2[TSprite,TSound].GetSwappedSprite (.TSprite original) (at Assets/Standard Assets/SpriterDotNet/Lib/SpriterAnimator.cs:327)
SpriterDotNet.SpriterAnimator`2[TSprite,TSound].Animate (Single deltaTime) (at Assets/Standard Assets/SpriterDotNet/Lib/SpriterAnimator.cs:249)
SpriterDotNetUnity.UnitySpriterAnimator.Animate (Single deltaTime) (at Assets/Standard Assets/SpriterDotNet/UnitySpriterAnimator.cs:42)
SpriterDotNet.SpriterAnimator`2[TSprite,TSound].Step (Single deltaTime) (at Assets/Standard Assets/SpriterDotNet/Lib/SpriterAnimator.cs:220)
SpriterDotNetUnity.SpriterDotNetBehaviour.Update () (at Assets/Standard Assets/SpriterDotNet/SpriterDotNetBehaviour.cs:63)

**Comment by treefortress** [comment]
Ok, figured it out. For some reason, the asset does not get marked as dirty, so the new sprites are not saved. Just had to add this to CreateSpriterData():
EditorUtility.SetDirty(data);

**Comment by loodakrawa** [comment]
I'm glad you managed to get it working. Based on your code, I don't see a way of making this work in a generic way. Also, I'm not happy with the library user needing to change the importer to customise the behaviour. Probably something like a Chain of Command would be good here. Having a default way of getting assets and allowing users to customise this behaviour by plugging in custom importers. Something similar as with the parsers:

https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterParser.cs#L28

What do you think?

**Comment by treefortress** [comment]
Yep this sounds ideal, as long as we can plugin somehow, and swap the images with images from another texture in Unity, be it 2dToolkit or TexturePacker, or NGUI, they all work pretty much the same.
