### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wighawag** [loodakrawa/SpriterDotNet#35]
I was reading your code and saw the following line : https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterProcessor.cs#L113

It is executed after GetBoneInfos which take a BoneInfo Array from the pool. 
This means that it can return before putting it back to the pool. If that happen these BoneInfos will never return to the pool causing a memory leak

**Comment by loodakrawa** [comment]
Nice catch! I'll fix it ASAP
