### ISSUE TITLE
animation.Timelines.Meta.Varlines's variables not updated if animation.Meta has no varLines

### ISSUE THREAD

**Issue by wighawag** [loodakrawa/SpriterDotNet#41]
I can see here : https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterParser.cs#L76
that if animation..meta has no varLines it return and thus do not proceed with animation.Timelines meta variables
This seems to be wrong

**Comment by loodakrawa** [comment]
Fixed in v1.3.2
