### ISSUE TITLE
Unity missing assets

### ISSUE THREAD

**Issue by alejodiazg** [loodakrawa/SpriterDotNet#42]
Im importing my project into unity after I import SpriterDotNet into my project, it imports the projects and creates the prefab, the problem is the console throws this error to me in all the images of my project 

    Missing Asset: Assets/Personaje/Partes esqueleto/esqueleto.png
    UnityEngine.Debug:Log(Object)
    SpriterDotNetUnity.SpriterImporter:LoadContent(String) (at Assets/SpriterDotNet/SpriterImporter.cs:238)
    SpriterDotNetUnity.<LoadAssets>c__Iterator17:MoveNext() (at Assets/SpriterDotNet/SpriterImporter.cs:227)
    System.Linq.Enumerable:ToArray(IEnumerable`1)
    SpriterDotNetUnity.SpriterImporter:CreateSpriterData(Spriter, String, String) (at Assets/SpriterDotNet/SpriterImporter.cs:87)
    SpriterDotNetUnity.SpriterImporter:CreateSpriter(String) (at Assets/SpriterDotNet/SpriterImporter.cs:50)
    SpriterDotNetUnity.SpriterImporter:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/SpriterDotNet/SpriterImporter.cs:34)
    UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
    UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
    UnityEditor.DockArea:OnGUI()

any idea what this could be? i need to do something with my project first?

**Comment by AndyGFX** [comment]
Hi, check if your images are sprite, if not, do it and then press Reimport on selected folder where is your Spriter animation. Second option is set your project as 2D, then unity always create from textures sprites.

Andy.

**Comment by loodakrawa** [comment]
What Andy said. I'll update the Unity documentation with this since it comes up rather often. Cheers
