### ISSUE TITLE
AnimationFinished(Name) dispatches repeatedly

### ISSUE THREAD

**Issue by treefortress** [loodakrawa/SpriterDotNet#43]
When a non-looping animation has finished, the AnimationFinished(Name) event will continuously fire.

In our case, we have a Death animation, when the death animation has finished, we want to re-parent our enemy to a corpses layer. Because the event fires many many times, it causes a bug in the game.

We can work around the issue, but still this can't be too good for performance. 

Ideally the onComplete event only fires once for every animation.

**Comment by loodakrawa** [comment]
Fixed in v1.3.2
