### ISSUE TITLE
Support charmap sprites with different pivot points

### ISSUE THREAD

**Issue by loodakrawa** [loodakrawa/SpriterDotNet#45]

**Comment by arthurtemple** [comment]
Fix on Java port on https://github.com/thorthur/gdx-spriter/commit/edf47e0491a122667fefc5affa648a34906d7002

My two cents as to what could be done, similarly to gdx-spriter:
- Leave pivot values to _NaN_ in [SpriterParser#InitInfos()](https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterParser.cs#L56)
- Add one more processing step when getting effective sprite ([around there I guess](https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterAnimator.cs#L243)) to check and replace _NaN_ values by pivot from the replacement file.

I can send a PR if you consider it the same way.

**Comment by loodakrawa** [comment]
Fixed in 1.4.0
