### ISSUE TITLE
Delete sprites in middle of the timeline, gives error when importing into unity

### ISSUE THREAD

**Issue by ghost** [loodakrawa/SpriterDotNet#52]
When you import an animation that have a deleted sprite in the timeline, when you try to import that animation in Unity, it give you errors.

For example:
An animation have some sprite in frame 0, and you delete that sprite in frame 10, when you try to import that animation, it give you the error

**Comment by loodakrawa** [comment]
Can you please provide more info? What exactly do you mean by deleting sprites? And what's the error you're getting?

**Comment by ghost** [comment]
![imagemissing00](https://cloud.githubusercontent.com/assets/17815839/13755320/7a670d28-e9f9-11e5-8cb8-d2094edd50eb.jpg)
![imagemissing01](https://cloud.githubusercontent.com/assets/17815839/13755324/7b157336-e9f9-11e5-801c-d664054ad9f1.jpg)
![imagemissing02](https://cloud.githubusercontent.com/assets/17815839/13755321/7a6d9814-e9f9-11e5-96da-a6e16a4bc56a.jpg)
![imagemissing03](https://cloud.githubusercontent.com/assets/17815839/13755322/7a71ed42-e9f9-11e5-8850-206c7217ec82.jpg)
![imagemissing04](https://cloud.githubusercontent.com/assets/17815839/13755323/7b10511c-e9f9-11e5-9841-cef4f7e62767.jpg)
![imagemissing05](https://cloud.githubusercontent.com/assets/17815839/13755325/7b2b044e-e9f9-11e5-92d2-24169bdc49c4.jpg)

In Spriter you can remove a sprite in the timeline and that creates a new key, when you import an animation who has removed sprites from the Hierarchy, when you try to import this animation in Unity, it give you errors

**Comment by loodakrawa** [comment]
Fixed in 1.4.0
