### ISSUE TITLE
Unity importer doesn't handle empty key tags properly

### ISSUE THREAD

**Issue by craigmjohnston** [loodakrawa/SpriterDotNet#54]
When a SCML file contains an animation with a key tag in the form: `<key id="7" time="450"/>` the importer creates a SpriterMainlineKey with a null ObjectRefs field, which throws a NullReferenceException in SpriterImporter.cs:307 when it tries to iterate over ObjectRefs ("`foreach (SpriterObjectRef obj in key.ObjectRefs)`").

I fixed it with a null check as a hack but I don't really know enough about the library to be confident that this is the right way to go about it.

**Comment by loodakrawa** [comment]
Fixed in 1.4.0
