### ISSUE TITLE
Preprocessing?

### ISSUE THREAD

**Issue by Dharengo** [loodakrawa/SpriterDotNet#55]
I like the event for postprocessing, but having something for preprocessing would be nice as well. Before I just modify the project myself, is such a thing already possible?

**Comment by loodakrawa** [comment]
At the moment - you can modify the loading process for assets via the [ContentLoader](https://github.com/loodakrawa/SpriterDotNet/blob/develop/SpriterDotNet.Unity/Assets/SpriterDotNet/SpriterImporter.cs#L29)

I also plan to extract the [initialisation logic](https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterParser.cs) for the data model itself to a separate class while allowing user to modify that process in a similar way as the IContentLoader.

**Comment by loodakrawa** [comment]
Added in v1.5.0. [Preprocessing](https://github.com/loodakrawa/SpriterDotNet/blob/develop/SpriterDotNet/SpriterReader.cs#L36)
