### ISSUE TITLE
Instantiate gameObject with animation as child.

### ISSUE THREAD

**Issue by AndyGFX** [loodakrawa/SpriterDotNet#58]
Hi,

I have very strange problem, when I drag converted animation to Unity in design mode, every animation works very well in run mode. 

Problem is when I instantiate prefab with animation to scene in run-time, then animation isn't played. I tried debug code, but looks like initialization was done and  play is executed.

Tried on empty scene withou any of my code.

I can't find problematic part.

Best regards,

AndyGFX.

**Comment by AndyGFX** [comment]
Hi,

additional info. I found where is maybe problem.

When first animation is with one frame withouth any changes (static) then when is object instantiated, animation doesn't works. But when first animation has more like one frame with any transition, instantiated prefab play all animation.

Andy.

**Comment by loodakrawa** [comment]
You'll have to provide additional info.

Have you tried with the latest from dev branch?
Are you getting any exceptions?
How do you instantiate the prefab during runtime?

**Comment by AndyGFX** [comment]
Was used 1.3.3 version SpriterDotNet with unity 5.3.4.
Instantiate via unity command from list of prefabs. No. I haven't any null
exception.

Andy.

**Comment by loodakrawa** [comment]
Try with the latest code from develop branch. Just remember to re-import the scml in question.

**Comment by AndyGFX** [comment]
Hi,

OK I will try it, but looks like SwapSprite(TSprite original, TSprite replacement); missing which I have used in project. Will by added or replaced with another method?

Andy.

**Comment by loodakrawa** [comment]
It's in SpriterAnimation.SpriteProvider

**Comment by AndyGFX** [comment]
Hi,

with dev. version all works well.

Thansk.

**Comment by loodakrawa** [comment]
Awesome, glad to hear that!
