### ISSUE TITLE
Sprites bug on transition

### ISSUE THREAD

**Issue by BrunoRomes** [loodakrawa/SpriterDotNet#61]
I'm experiencing a strange bug when using transitions of animations, where the sprites start to rotate and strech. These can be seen in the screens below.

![Idle](https://cloud.githubusercontent.com/assets/1671638/15624646/cc128054-2463-11e6-93b8-511912525c41.png)
![Transition From Idle to Walk 1](https://cloud.githubusercontent.com/assets/1671638/15624647/cc13aa92-2463-11e6-9196-18569568acb3.png)
![Transition From Idle to Walk 2](https://cloud.githubusercontent.com/assets/1671638/15624648/cc25cb5a-2463-11e6-95e5-bbcde80c0f6f.png)
![Walk](https://cloud.githubusercontent.com/assets/1671638/15624649/cc26a610-2463-11e6-880b-fd127a540f88.png)
![Transition From Walk to Idle](https://cloud.githubusercontent.com/assets/1671638/15624650/cc299e1a-2463-11e6-8987-0c29f880aea4.png)

These animations were taken from the Adventure Pack (and stripped down, now I only have idle and walk animations), but I still can't seem to find the problem. To help in the analysis I created a test project (that can be accessed [here](https://github.com/BrunoRomes/SpriterDotNetBugReport) ).

My setup:
- Linux Mint 17.3
- Spriter Pro Release 8
- Unity 5.3.4f1 64bits linux version

**Comment by loodakrawa** [comment]
Hey, I didn't see this until now - didn't get an email as I usually do. Anyway, I'll investigate this as soon as I find the time.

**Comment by loodakrawa** [comment]
Did you get the same issue on any other .scml files? I can't find the issue with this one and it seems to be working fine for all others. I suspect it might be something specific just to this .scml file.
