### ISSUE TITLE
Flipping doesnt work

### ISSUE THREAD

**Issue by bosoni** [loodakrawa/SpriterDotNet#67]
When I flip animation (changing AtlasExample/0.scml x-direction), pieces goes wrong places.

Test:
Added 
if (IsPressed(Keys.Tab)) currentAnimator.Scale = new Vector2(-1f, 1f);  
to SpriterGameState.cs.

![spr](https://cloud.githubusercontent.com/assets/2569545/18392630/268db450-76bb-11e6-81dd-400dff13e5bb.jpg)

**Comment by loodakrawa** [comment]
That's in the feature/texture-atlas branch, right? It's still work in progress. The develop branch should be working fine (without texture atlases though). Thanks for reporting - I wasn't aware of this.

**Comment by bosoni** [comment]
Yes, feature/texture-atlas branch.

**Comment by loodakrawa** [comment]
Fixed with the latest commit on feature/texture-atlas
