### ISSUE TITLE
StopPlayback & StartPlayback

### ISSUE THREAD

**Issue by llafuente** [loodakrawa/SpriterDotNet#72]
Hi,

I'm looking for a counter part for those functions that UnityEngine.Animator has.

I see Animator.Speed is this the preferred way ?

**Comment by loodakrawa** [comment]
I'm not really familiar with Unity's Animator. What exactly is the functionality you're trying to achieve?

**Comment by llafuente** [comment]
Freeze the animation and resume

I have this (untested):

```
    public override PlaybackSpeed(float speed) {
      previousSpeed = animator.Speed;
      animator.Speed = speed;
    }

    public override StopPlayback() {
      previousSpeed = animator.Speed;
      animator.Speed = 0;
    }

    public override StartPlayback() {
      animator.Speed = previousSpeed ? previousSpeed : 1;
      previousSpeed = 0;
    }
```

**Comment by loodakrawa** [comment]
Ah, yes. You can set the Speed to 0 or alternatively you can just skip calling the [Update method on the Animator](https://github.com/loodakrawa/SpriterDotNet/blob/develop/SpriterDotNet.Unity/Assets/SpriterDotNet/SpriterDotNetBehaviour.cs#L78).
