### ISSUE TITLE
MonoGame: Add a way to scale a sprite without deforming the texture

### ISSUE THREAD

**Issue by Noxalus** [loodakrawa/SpriterDotNet#75]
Hello everyone :)

I'm looking for a way to repeat a texture on a sprite that we scale instead of stretching it out. 

I ask the same question on the Spriter forum ([here](https://brashmonkey.com/forum/index.php?/topic/5015-stretch-out-animation/)), but I would like to avoid to manually create multiple sprites for that :/

Do you have any idea of what will be the easiest way to do that?

**Comment by loodakrawa** [comment]
Just to make sure I understand correctly - you want to scale the cane and have the white/red background NOT scale but just show under the cane shape?

**Comment by Noxalus** [comment]
Yes, that's what I would like to do, here is an image to better understand:

![](http://community.monogame.net/uploads/default/original/2X/c/ca6d36c12220311ab4db04e7d67227f656b2c30d.jpg)

From left to right:
- The original image
- The image scaled without using UV scaling
- The image scaled using the UV scaling

**Comment by loodakrawa** [comment]
This is not something supported out of the box. Probably the best thing you can do is extend [Animator](https://github.com/loodakrawa/SpriterDotNet/blob/develop/SpriterDotNet/Animator.cs) and then use some kind of custom logic (sprite masking?) to achieve this effect. Take a look at [MonoGameAnimator](https://github.com/loodakrawa/SpriterDotNet/blob/feature_texturepacker_support/SpriterDotNet.MonoGame/MonoGameAnimator.cs) to see how to implement it. Note that this is a link to a feature branch that's different from the main one.
